### ISSUE TITLE
enquiry balance from node return empty result

### ISSUE THREAD

**Issue by 2pd** [aeternity/protocol#19]
epoch running fine in my node, but when I try to enquiry the balance, I have problem:

```bash
jeremy@manager:~/0.5$ curl http://127.0.0.1:3103/v2/account/pub-key

{"pub_key":"ak$3QoJpkpFAtr37mE25VUSraJPQc5B23FN3kFzDSJdqFnVBSVPg5fjLPtJDSp3eRDHYZsDqaVRzno21WvzeCAQouugoBh5DB"}
```
when I try to check balance as suggested
>curl -G http://127.0.0.1:3013/v2/account/balance --data-urlencode 'pub_key=ak$3N1WLMewMQPUyQBdEhXRSYee84RQNKJrECwbbseMkNsZhv1XLjpmiqjAkvSRpQ6kgWJMjq9dTmdQ3ekuhpscJk6LpjJYk4'

```bash
curl -G http://127.0.0.1:3013/v2/account/balance --data-urlencode 'pub_key=ak$3QoJpkpFAtr37mE25VUSraJPQc5B23FN3kFzDSJdqFnVBSVPg5fjLPtJDSp3eRDHYZsDqaVRzno21WvzeCAQouugoBh5DB'

curl: (7) Failed to connect to 127.0.0.1 port 3013: Connection refused
```

So I think the port number is wrong in the doc and change to 
```bash
curl -G http://127.0.0.1:3103/v2/account/balance --data-urlencode 'pub_key=ak$3QoJpkpFAtr37mE25VUSraJPQc5B23FN3kFzDSJdqFnVBSVPg5fjLPtJDSp3eRDHYZsDqaVRzno21WvzeCAQouugoBh5DB'

{}
```
So the above returning empty map.

I'm sure that I have mined some blocks, when listening to websocket, i can see some log:

```bash
< {"action":"mined_block","origin":"miner","payload":{"height":1005,"hash":"bh$ZYedc5XzBhwgu1hmjoqNknZWo9doTqmE88c9JAdBE8faLqoYD"}}
< {"action":"mined_block","origin":"miner","payload":{"height":1028,"hash":"bh$3PqkmMJPGCJo1a1tn3L4jkmiJTbRH6wqQ9Rj7Xnd5BLSMwKyJ"}}
< {"action":"mined_block","origin":"miner","payload":{"height":1032,"hash":"bh$fG2JZb1vSUr25V6ANxLZRxYcAm7NzjpWr2PS3LQsXNVkeeEnS"}}
< {"action":"mined_block","origin":"miner","payload":{"height":1053,"hash":"bh$2MqBwDAikt6UCNhWau9MFM4RGSxzY5pdxVxvjAVguJTShkwP6d"}}
```

Thanks

**Comment by velzevur** [comment]
Hi @2pd 
Thank you for your nice description.
What are your endpoint settings? As stated [here](https://github.com/aeternity/protocol/blob/master/epoch/api/account_api_usage.md) there is an external endpoint port and an internal one. In the example there they were defined as
```
HTTP external API: 3013
HTTP internal API: 3113
```
and all tests were running with thar presumption.
`/v2/account/pub-key` is part of the internal HTTP API
`/v2/account/balance` is part of the external one. You should check what your external port is and addapt your curl request to the correct port.

Since this is an external HTTP API, one could use any node to make a request to. One of the public nodes as defined [here](https://github.com/aeternity/epoch/blob/v0.5.0/RELEASE-NOTES.md#inspect-the-testnet)  is `http://31.13.248.103` and its public HTTP API port is 3013.
```
$ curl -G http://31.13.248.103:3013/v2/account/balance --data-urlencode 'pub_key=ak$3QoJpkpFAtr37mE25VUSraJPQc5B23FN3kFzDSJdqFnVBSVPg5fjLPtJDSp3eRDHYZsDqaVRzno21WvzeCAQouugoBh5DB'

{"balance":305}
```

In order to do this on your own node, please consult your `epoch.yaml` for your external API port and use it in your curl request.

**Comment by 2pd** [comment]
Thank you for your explanation, I need more understanding of the system.
All good, thank you for your time , you guys are doing great job.
