### ISSUE TITLE
Can we get rid of the error logging pollution, please?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#40]
It seems that every exception that is thrown during transaction processing is reposted to the epoch.log over and over again which makes development almost impossible after a couple of bad transactions have been produced. In addition this now seems to affect server stability.

**Comment by hanssv** [comment]
The problem is that bad transactions are not removed from the mempool and thus for every mining attempt there will be a (bad) transaction to reconsider, and fail... The mempool will be given an overhaul during the current sprint so hopefully most of this will be solved by that:
https://www.pivotaltracker.com/story/show/152473613
https://www.pivotaltracker.com/story/show/152796665
https://www.pivotaltracker.com/story/show/154339293

**Comment by tillkolter** [comment]
@hanssv That raises another question. How will the `account_nonce_too_high` errors will be handled? I guess that you will treat them like on Ethereum where a tx ideally stays in the pool until a tx with `nonce - 1` will be mined with the pool being occasionally cleared from these kind of unprocessed transactions after a reasonable amount of time? And will there be a threshold (as in Ethereum) for maximum number of `account_nonce_too_high` errors per account?

**Comment by hanssv** [comment]
I've got no insight in the exact details...
