### ISSUE TITLE
How are oracle providers meant to be implemented?

### ISSUE THREAD

**Issue by tillkolter** [aeternity/protocol#46]
Right now we implemented examples for Python/NodeJS and Browser. Does this even make sense if the input/output formats are later to be specified as types of the smart contract language. Can we cast to these types later or do the oracles themselves have to be ported to the smart contract language?

**Speaking of formats...**
Are the formats expected to be atomic types or will it also be possible to have tuples?

**Comment by hanssv** [comment]
I don't think we have considered any special Oracle limitations for the types. Since oracle information (mostly responses I guess) will be used from contracts it makes sense to reuse the type specifications from contracts. I don't expect the contract types to be very exotic - i.e. you should be able to convert them to corresponding types in most languages?! 

I also guess an oracle could _by pass_ the type validation by saying a query is a string and the response is a string...

Personally I'd write my Oracles in Erlang of course :-)

**Comment by tillkolter** [comment]
Ok, I think thats all I wanted to know for now :)
