### ISSUE TITLE
Allow ML-style block comments [recommendation]

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/protocol#97]
As plenty syntax highlighters for functional languages use `(* *)` for block comments by default

**Comment by radrow** [comment]
<necro bump> 
Personally I don't like this notation, because if we wanted to add prefix notation of operators (i.e. `a + b == (+)(a, b)`) the `(*)` function would cause some problems. Also, `//` and `/*` are more popular than `(* *)` which are common only in ML like languages. 

Also, this should be moved to `aesophia` repo
